### PR TITLE
Increase SAV_MEM_BSZ to 1111111 bytes.

### PR DESCRIPTION
**Pull request by hedj**
On my 1104Z, this triples the speed of saving 24M points.

### CODE REVIEW

**Comment by Teuniz** [comment]
Hello Hedj, thank you for contributing.
Unfortunately I can't apply your patch because Rigol's programming guide says that the maximum number of bytes that can be read each time must not exceed 250000.

**Comment by hedj** [comment]
The MSO/DS1000Z manual does not include such a statement. Is this for other
scopes?

**Comment by Teuniz** [comment]
I guess we are using different versions of Rigol's programming guide.
Mine's from July 2015. Is it the same as yours?

**Comment by hedj** [comment]
Aha! That does seem to be it:

I was using this one:
http://www.batronix.com/pdf/Rigol/ProgrammingGuide/MSO1000Z_DS1000Z_ProgrammingGuide_EN.pdf

Which seems to be from 2014. Do you have a link/copy of the updated version?

Thanks,
John

On Fri, Feb 5, 2016 at 9:46 PM, Teuniz <notifications@github.com> wrote:

> I guess we are using different versions of Rigol's programming guide.
> Mine's from July 2015. Is it the same as yours?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Teuniz/DSRemote/pull/1#issuecomment-180291491>.
>



-- 
 "Don't worry about people stealing an idea. If it's original, you will
have to ram it down their throats"  - Howard Aiken.

**Comment by Teuniz** [comment]
I just discovered that there's even a newer one, from December 2015....
Here's the link:
[http://beyondmeasure.rigoltech.com/acton/attachment/1579/f-0386/1/-/-/-/-/DS1000Z_Programming%20Guide_EN.pdf](url)
I haven't read it yet so I don't know what has changed this time.

**Pull request closed without merging**
