### PR TITLE
Add rudimentary support for MSO4000 series

### PR DESCRIPTION
**Pull request by momu**
I added support for the MSO4000/DS4000 series.
Basic functionality like connecting, setting trigger levels and changing position is working.

I've not tested these functions:

* Record & Playback function
* Wave Inspector
* serial decoding.

### CODE REVIEW

**Comment by Teuniz** [comment]
Thanks for the offer but I have some thoughts about it:

1. I don't own an MSO/DS4000 series scope. That means it will be impossible for me to test and maintain the code for this series. But still people will come to me to ask for fixes...

2. You didn't check and tested all functions. I don't want to release untested code.

3. I advise you to do a git grep "modelserie ==" in order to find all occurrences in all files where you very likely need to make modifications, more or less in the same way you already did in other parts.

4. Question, you already downloaded the latest version of the programming guide (August 2016) and started to look for differences in behaviour & parameter ranges for the commdands used?

**Comment by momu** [comment]
I fully understand your concerns.
Let me describe what I've done so far (which is basically what you suggested).

I grepped for `devparms->modelserie == 6` and replaced it with `devparms->modelserie == 6 || devparms->modelserie == 4` where commands `tmc_write` or `set_cue_cmd` calls are involved. I verified the commands against the programming guide from August 2016 (same for `devparms->modelserie != 6` -> `devparms->modelserie != 6 && devparms->modelserie != 4`).

But I didn't change these lines – because I was not 100% sure what is happening there): 
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/wave_view.cpp#L969
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/signalcurve.cpp#L343
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/signalcurve.cpp#L799
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/signalcurve.cpp#L2325
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/decode_dialog.cpp#L189
https://github.com/Teuniz/DSRemote/blob/b03aafc262049c0be4d0a80910c253db9c78ca5e/playback_dialog.cpp#L236

Maybe you can help me a bit on these lines?

> Question, you already downloaded the latest version of the programming guide (August 2016) and started to look for differences in behavior & parameter ranges for the commands used?

I just checked if the commands exist. Parameter ranges are still open.

Do you have a kind of standard test case or a list of tests which you usually perform so that I can test my changes against?

As I have access to MSO4000 series scopes I could keep an eye on the complaints/fixes – as long as it will not become a day filling thing.

**Comment by Teuniz** [comment]
I merged your commit and after that I pushed some modifications.
Could you check if the verticale scale / sensitivity is correct and if the waveforms have the same size as on the scope's display?
Could you also check the USB connection?
Can you tell me the vid & pid of the scope USB connection? You can use the command lsusb for that.

**Comment by momu** [comment]
> Could you check if the verticale scale / sensitivity is correct and if the waveforms have the same size as on the scope's display?

Vertical scale seems ok, vertical sensitivity is not. Time scale is ok. Meaning trigger level is on same 
position on scope display and in DSRemote. But signal amplitude appears to be 1/3 bigger in DSRemote than on scope. Where is the place to fix it?

> Could you also check the USB connection? 

As I only tried the USB connection, I tried the network this time. Works both.

> Can you tell me the vid & pid of the scope USB connection?

```
$ lsusb 
Bus 003 Device 004: ID 1ab1:04b1 Rigol Technologies
```

**Comment by Teuniz** [comment]
I changed the shortcut for the screenshot from 'p' to ctrl+p.
Can you pull again and test the sensitivity again?
If the sensitivity is ok, can you test the extended vertical range setting?
Thanks.

**Comment by momu** [comment]
Sensitivity is not ok. Extended vertical range setting works. 
Btw. what's the purpose of the extended vertical range setting.

Scope's screenshot:
screenshot_scope

DSRemote screenshot
screenshot_dsremote

DSRemote screenshot (extended vertical range)
screenshot_dsremote_extended

**Comment by Teuniz** [comment]
Pls pull again and recompile. Let me know if sensitivity is ok.

**Comment by Teuniz** [comment]
And again, we are now at version 0.35_1710210945.
I removed the "extended vertical range" setting for the 4000 series because it makes sense only for the 1000Z series.
The reason is, the scope uses an 8-bit ADC and because of that there are 256 steps in vertical direction. The 1000Z series shows only max. 200 steps of vertical resolution while when you download the waveform data, all 256 steps are available. Using the extended vertical range, DSRemote is able to use/show the full dynamic range of the ADC while the scope itself can not.

**Comment by momu** [comment]
Sensitivity is fine now. Thanks

**Pull request merged**
